const { withAppBuildGradle } = require('expo/config-plugins');

// Injects a release signingConfig (driven by env vars) into the build.gradle
// generated by `expo prebuild`, since android/ is not committed.
const RELEASE_SIGNING_CONFIG = `        release {
            storeFile file(System.getenv("ANDROID_KEYSTORE_PATH") ?: "sobre.keystore")
            storePassword System.getenv("ANDROID_KEYSTORE_PASSWORD") ?: ""
            keyAlias System.getenv("ANDROID_KEY_ALIAS") ?: ""
            keyPassword System.getenv("ANDROID_KEY_PASSWORD") ?: ""
        }`;

function applyReleaseSigning(buildGradle) {
  if (buildGradle.includes('ANDROID_KEYSTORE_PATH')) {
    return buildGradle;
  }

  let gradle = buildGradle.replace(
    /signingConfigs\s*\{/,
    `signingConfigs {\n${RELEASE_SIGNING_CONFIG}`
  );

  // Point the release build type at the release signing config instead of
  // the debug keystore the Expo template defaults to.
  gradle = gradle.replace(
    /(buildTypes\s*\{[\s\S]*?release\s*\{[^}]*?)signingConfig signingConfigs\.debug/,
    '$1signingConfig signingConfigs.release'
  );

  return gradle;
}

module.exports = function withAndroidSigning(config) {
  return withAppBuildGradle(config, (config) => {
    if (config.modResults.language !== 'groovy') {
      throw new Error('withAndroidSigning: expected a groovy build.gradle');
    }
    config.modResults.contents = applyReleaseSigning(config.modResults.contents);
    return config;
  });
};
